/**
 * Request/response shapes for the backend team's Supabase Edge Functions
 * (register2/supabase/functions/*). These mirror what the functions
 * actually return — keep them in sync with the backend, not the other way
 * round.
 */

/** registrations.selected_day */
export type RegistrationDay = 'DAY_1' | 'DAY_2' | 'BOTH' | 'SPECIAL'

/** Team packages exist only for single days. */
export type TeamDay = 'DAY_1' | 'DAY_2'

/** get-registration-fees (GET) */
export interface RegistrationFees {
  DAY_1: number
  DAY_2: number
}

/** rpc/get_special_events */
export interface SpecialEvent {
  code: string
  name: string
  description?: string | null
  fee: number
}

/** public-register (multipart/form-data) */
export interface PublicRegisterInput {
  name: string
  email: string
  phone: string
  college: string
  department: string
  year: string
  /** No longer collected by the site; sent only if provided. */
  utr?: string
  selectedDay: RegistrationDay
  specialEventCodes: string[]
  /** No longer collected by the site; sent only if provided. */
  paymentScreenshot?: File
}

export interface PublicRegisterResponse {
  success: true
  registration_code: string
  status: 'UNDER_REVIEW'
}

/** check-registration */
export interface CheckRegistrationResponse {
  participant: { name: string; college: string; department: string; year: string | null }
  registration: { registration_code: string; selected_day: RegistrationDay; status: string }
  team_events: { id: string; code: string; name: string; day: string; event_type: string }[]
  special_events: { id: string; code: string; name: string; fee: number }[]
  payment: { amount: number; status: string; utr_masked: string } | null
  team: {
    team_code: string
    team_name: string
    status: string
    event_name: string
    members: { name: string; member_role: string }[]
  } | null
  /** Present only when payment is VERIFIED and registration is CONFIRMED. */
  qr_url: string | null
}

/** team-management */
export interface TeamPackage {
  /** `${day}:${size}` — generated by the backend, sent back as package_id */
  id: string
  day: TeamDay
  size: number
  events: { id: string; code: string; name: string }[]
}

export interface TeamVerifyResponse {
  success: true
  registration: {
    id: string
    registration_code: string
    selected_day: RegistrationDay
    participant_name: string
  }
  packages: Record<TeamDay, TeamPackage[]>
}

export interface TeamCreateInput {
  /** Leader's registered email or Registration ID */
  identity: string
  /** Other members' registered emails or Registration IDs */
  members: string[]
  day: TeamDay
  packageId: string
  teamName: string
}

export interface TeamCreateResponse {
  success: true
  message: string
  team: {
    id: string
    team_code: string
    team_name: string
    package_events: { id: string; code: string; name: string }[]
  }
}

/** Mirrors the backend client's `cs_last_registration` localStorage record. */
export interface LastRegistration {
  code: string
  email: string
  phone: string
}
